// GENERATED by tools/make_designer_data.py — don't edit by hand; re-run the script.
// A stand-in `Backend` for visual QML editors and the `qml` previewer: the real theme,
// settings and demo library, with every action doing nothing.
pragma Singleton
import QtQuick

QtObject {

    property bool fake: true
    property bool firstRun: false
    property real motion: 1
    property int artTick: 0
    property int artGen: 0
    property int headerTick: 0

    signal libraryError(string details)
    signal headerImageFailed(string message)

    function launch(id) { return "test" }
    function gameInfo(id) { return ({}) }
    function titleOf(id) { return "" }
    function headerOf(id) { return "launcher" }
    function headerTextOf(id) { return "" }
    function setHeader(id, mode) {}
    function setHeaderText(id, t) {}
    function setHeaderImage(id, p) {}
    function isInstalled(id) { return true }
    function isFavorite(id) { return false }
    function setFavorite(id, on) {}
    function playtimeEditable(id) { return false }
    function playtimeHours(id) { return "0" }
    function setPlaytime(id, t) { return true }
    function artRevOf(id) { return 0 }
    function soundUrl(name) { return "" }
    function openUrl(u) {}
    function rename(id, t) {}
    function setHidden(id, h) {}
    function setNoSlot(id, v) {}
    function addGame(n, c) { return "" }
    function removeCustomGame(id) {}
    function relatedOf(id) { return "" }
    function setRelated(id, n) {}
    function processesSince(id) { return [] }
    function libraryIdForApp(a) { return "" }
    function libraryProblems() { return "" }
    function logFile() { return "" }
    function localPath(u) { return u }
    function launcherSummary() { return "" }
    function setupFinished() {}
    function rescan() {}
    function cacheSize() { return "12 MB" }
    function clearCache() { return "12 MB" }
    function resetSettings() {}
    function demoFinishInstall(id) {}

    property QtObject theme: QtObject {
        signal changed()
        property var p: ({"shellTop": "#3c3c41", "shellBottom": "#222226", "shellSide": "#0b0b0d", "shellHi": "#40ffffff", "shellLo": "#80000000", "groove": "#18181b", "stickerHead": "#1c1c1f", "stickerEdge": "#99000000", "stickerSheen": "#14ffffff", "artBack": "#000000", "labelBack": "#0b0b0c", "headerText": "#f4f4f4", "labelText": "#f0f0f0", "grain": 0.07, "tray": "#2a2a2e", "trayShade": "#40000000", "recess": "#1c1c1f", "recessHi": "#26ffffff", "engrave": "#6a6a70", "engraveHi": "#14ffffff", "trayText": "#e8e8ea", "trayTextDim": "#a2a2a8", "dockTop": "#3a3a3e", "dockBottom": "#202023", "dockHi": "#40ffffff", "dockSeam": "#000000", "dockText": "#f0f0f2", "dockTextDim": "#a8a8ae", "ledOff": "#48484c", "shadow": "#000000", "dangerText": "#ff6f66", "panel": "#2b2b30", "panelText": "#f2f2f4", "panelTextDim": "#a9a9b1", "panelBorder": "#3d3d44", "panelHover": "#3a3a41", "scrim": "#a6000000", "display": "#0e1012", "displayText": "#e8efec", "displayDim": "#8d9a96", "shadowStrength": 0.55, "isDark": true})
        property var cp: p
        property var accent: ({"accent": "#0b78b8", "accentHover": "#09659b", "accentText": "#ffffff", "danger": "#d33a31"})
        property var led: ({"green": "#35c46a", "amber": "#f0a232"})
        property var geo: ({"radius": 36, "thickness": 12, "sticker": [44, 60, 512, 714, 20], "tab": [206, 34, 188, 28, 10], "header": [44, 60, 512, 172], "art": [44, 232, 512, 454], "label": [44, 686, 512, 88], "arrow": [248, 798, 104, 42], "notch": [708, 54, 10], "stickerWell": 5, "pins": {"count": 11, "width": 20, "gap": 9.6, "height": 64}})
        property real ratio: 1.4633333333333334
        property string edition: "dark"
        property string cardEdition: "dark"
        property bool dark: true
        property string texQuery: ""
        property string hardware: "black"
        property string cardColor: "same"
        property var hardwareOptions: [{"value": "black", "text": "Black", "color": "#3c3c41"}, {"value": "white", "text": "White", "color": "#ffffff"}, {"value": "pink", "text": "Pink", "color": "#fac9dd"}, {"value": "mint", "text": "Mint", "color": "#bbebd9"}, {"value": "neon", "text": "Neon", "color": "#c4f75c"}, {"value": "atomic", "text": "Atomic Purple", "color": "#8065c2"}, {"value": "red", "text": "Red", "color": "#de5257"}]
        function tones(h) { return [{"name": "Pastel", "color": "#badbff"}, {"name": "Light", "color": "#8ac3fd"}, {"name": "Medium", "color": "#4c9deb"}, {"name": "Deep", "color": "#1f6cb0"}, {"name": "Dark", "color": "#154470"}] }
        function harmonies(c) { return [{"group": "Calm", "name": "Analogous", "color": "#b46662"}, {"group": "Calm", "name": "Analogous", "color": "#9d6aa2"}, {"group": "Bold", "name": "Complementary", "color": "#458f7b"}, {"group": "Bold", "name": "Split", "color": "#5d8d5c"}, {"group": "Bold", "name": "Split", "color": "#298f98"}, {"group": "Playful", "name": "Triadic", "color": "#7f8639"}, {"group": "Playful", "name": "Triadic", "color": "#3689b2"}, {"group": "Classic", "name": "Black", "color": "#3c3c41"}, {"group": "Classic", "name": "White", "color": "#ffffff"}] }
        function plasticOf(v) { return "#3c3c41" }
        function hueOf(c) { return 250 }
        function customValue(c) { return "c_" + c.replace("#", "") }
    }

    property QtObject settings: QtObject {
        signal changed()
        property bool tiltEnabled: true
        property bool soundsEnabled: true
        property bool showTitles: true
        property int cardWidth: 150
        property real soundVolume: 0.3
        property string hardware: "black"
        property bool texturedPlastic: true
        property bool preferOfficialArt: false
        property string sortMode: "recent"
        property string filterMode: "all"
        property var hidden: []
        property var noSlot: []
        property var titles: ({})
        property var headers: ({})
        property var headerTexts: ({})
        property var sgdbIds: ({})
        property var soundChoice: ({"release": "release_2.wav"})
        property string cardColor: "same"
        property bool testCartridge: false
        property var related: ({})
        property bool installedFirst: false
        property bool checkUpdates: true
        property bool setupDone: false
        property bool hideAdult: true
        property var favorites: []
        property bool crtEffects: true
    }

    property ListModel favorites: ListModel {
        function rowOf(id) { return -1 }
        function idAt(r) { return "" }
    }

    property ListModel games: ListModel {
        property string filterText: ""
        property string filterMode: "all"
        property string sortMode: "recent"
        function rowOf(id) { for (let i = 0; i < count; i++) if (get(i).gameId === id) return i; return -1 }
        function idAt(r) { return r >= 0 && r < count ? get(r).gameId : "" }
        ListElement { gameId: "fake0"; title: "Starfall Odyssey"; source: "steam"; sourceName: "STEAM"; sourceIcon: "steam"; code: "STOD"; extId: "1200000"; installed: true; noSlot: false; lastPlayed: 1790466595; added: 1788392995; hidden: false; playtime: 0; developer: ""; publisher: ""; released: 0 }
        ListElement { gameId: "fake1"; title: "Moss & Lantern"; source: "steam"; sourceName: "STEAM"; sourceIcon: "steam"; code: "MOLA"; extId: "1207919"; installed: true; noSlot: false; lastPlayed: 1790207395; added: 1788479395; hidden: false; playtime: 0; developer: ""; publisher: ""; released: 0 }
        ListElement { gameId: "fake2"; title: "Neon Drift II"; source: "steam"; sourceName: "STEAM"; sourceIcon: "steam"; code: "NEDR2"; extId: "1215838"; installed: false; noSlot: false; lastPlayed: 0; added: 1788565795; hidden: false; playtime: 0; developer: ""; publisher: ""; released: 0 }
        ListElement { gameId: "fake3"; title: "The Quiet Harbor"; source: "steam"; sourceName: "STEAM"; sourceIcon: "steam"; code: "QUHA"; extId: "1223757"; installed: true; noSlot: false; lastPlayed: 1789688995; added: 1788652195; hidden: false; playtime: 0; developer: ""; publisher: ""; released: 0 }
        ListElement { gameId: "fake4"; title: "Ironbound: Siege of Vael"; source: "steam"; sourceName: "STEAM"; sourceIcon: "steam"; code: "IRON:SOV"; extId: "1231676"; installed: true; noSlot: false; lastPlayed: 1789429795; added: 1788738595; hidden: false; playtime: 0; developer: ""; publisher: ""; released: 0 }
        ListElement { gameId: "fake5"; title: "Pixel Parade"; source: "steam"; sourceName: "STEAM"; sourceIcon: "steam"; code: "PIPA"; extId: "1239595"; installed: true; noSlot: false; lastPlayed: 1789170595; added: 1788824995; hidden: false; playtime: 0; developer: ""; publisher: ""; released: 0 }
        ListElement { gameId: "fake6"; title: "Hollow Pines"; source: "heroic"; sourceName: "HEROIC"; sourceIcon: "com.heroicgameslauncher.hgl"; code: "HOPI"; extId: "hopi"; installed: true; noSlot: false; lastPlayed: 1788911395; added: 1788911395; hidden: false; playtime: 0; developer: ""; publisher: ""; released: 0 }
        ListElement { gameId: "fake7"; title: "Tidebreaker"; source: "lutris"; sourceName: "LUTRIS"; sourceIcon: "lutris"; code: "TIDE"; extId: "tide"; installed: true; noSlot: false; lastPlayed: 1788652195; added: 1788997795; hidden: false; playtime: 0; developer: ""; publisher: ""; released: 0 }
        ListElement { gameId: "fake8"; title: "Garden Sprites"; source: "flatpak"; sourceName: "FLATPAK"; sourceIcon: "applications-games"; code: "GASP"; extId: "gasp"; installed: true; noSlot: false; lastPlayed: 1788392995; added: 1789084195; hidden: false; playtime: 0; developer: ""; publisher: ""; released: 0 }
        ListElement { gameId: "fake9"; title: "Skyward Postman"; source: "steam"; sourceName: "STEAM"; sourceIcon: "steam"; code: "SKPO"; extId: "1271271"; installed: true; noSlot: false; lastPlayed: 1788133795; added: 1789170595; hidden: false; playtime: 0; developer: ""; publisher: ""; released: 0 }
        ListElement { gameId: "fake10"; title: "Dungeon Bakery"; source: "steam"; sourceName: "STEAM"; sourceIcon: "steam"; code: "DUBA"; extId: "1279190"; installed: false; noSlot: false; lastPlayed: 0; added: 1789256995; hidden: false; playtime: 0; developer: ""; publisher: ""; released: 0 }
        ListElement { gameId: "fake11"; title: "Retro Racer DX"; source: "steam"; sourceName: "STEAM"; sourceIcon: "steam"; code: "RRD"; extId: "1287109"; installed: true; noSlot: false; lastPlayed: 1787615395; added: 1789343395; hidden: false; playtime: 0; developer: ""; publisher: ""; released: 0 }
        ListElement { gameId: "fake12"; title: "Aurora Protocol"; source: "steam"; sourceName: "STEAM"; sourceIcon: "steam"; code: "AUPR"; extId: "1295028"; installed: true; noSlot: false; lastPlayed: 1787356195; added: 1789429795; hidden: false; playtime: 0; developer: ""; publisher: ""; released: 0 }
        ListElement { gameId: "fake13"; title: "Cozy Burrow"; source: "steam"; sourceName: "STEAM"; sourceIcon: "steam"; code: "COBU"; extId: "1302947"; installed: true; noSlot: false; lastPlayed: 1787096995; added: 1789516195; hidden: false; playtime: 0; developer: ""; publisher: ""; released: 0 }
        ListElement { gameId: "fake14"; title: "Paper Knights"; source: "heroic"; sourceName: "HEROIC"; sourceIcon: "com.heroicgameslauncher.hgl"; code: "PAKN"; extId: "pakn"; installed: true; noSlot: false; lastPlayed: 1786837795; added: 1789602595; hidden: false; playtime: 0; developer: ""; publisher: ""; released: 0 }
        ListElement { gameId: "fake15"; title: "Void Salvage"; source: "steam"; sourceName: "STEAM"; sourceIcon: "steam"; code: "VOSA"; extId: "1318785"; installed: false; noSlot: false; lastPlayed: 0; added: 1789688995; hidden: false; playtime: 0; developer: ""; publisher: ""; released: 0 }
        ListElement { gameId: "fake16"; title: "Lighthouse Keeper"; source: "steam"; sourceName: "STEAM"; sourceIcon: "steam"; code: "LIKE"; extId: "1326704"; installed: true; noSlot: false; lastPlayed: 1786319395; added: 1789775395; hidden: false; playtime: 0; developer: ""; publisher: ""; released: 0 }
        ListElement { gameId: "fake17"; title: "Mech Tactics: Frontier"; source: "epic"; sourceName: "EPIC GAMES"; sourceIcon: "applications-games"; code: "META:F"; extId: "meta:f"; installed: true; noSlot: false; lastPlayed: 1786060195; added: 1789861795; hidden: false; playtime: 0; developer: ""; publisher: ""; released: 0 }
        ListElement { gameId: "fake18"; title: "Harvest Moonlight"; source: "riot"; sourceName: "RIOT"; sourceIcon: "applications-games"; code: "HAMO"; extId: "hamo"; installed: true; noSlot: false; lastPlayed: 1785800995; added: 1789948195; hidden: false; playtime: 0; developer: ""; publisher: ""; released: 0 }
        ListElement { gameId: "fake19"; title: "Frostbyte"; source: "lutris"; sourceName: "LUTRIS"; sourceIcon: "lutris"; code: "FROS"; extId: "fros"; installed: true; noSlot: false; lastPlayed: 1785541795; added: 1790034595; hidden: false; playtime: 0; developer: ""; publisher: ""; released: 0 }
        ListElement { gameId: "fake20"; title: "Sunset Arcade"; source: "steam"; sourceName: "STEAM"; sourceIcon: "steam"; code: "SUAR"; extId: "1358380"; installed: false; noSlot: false; lastPlayed: 0; added: 1790120995; hidden: false; playtime: 0; developer: ""; publisher: ""; released: 0 }
        ListElement { gameId: "fake21"; title: "Clockwork Fox"; source: "steam"; sourceName: "STEAM"; sourceIcon: "steam"; code: "CLFO"; extId: "1366299"; installed: true; noSlot: false; lastPlayed: 1785023395; added: 1790207395; hidden: false; playtime: 0; developer: ""; publisher: ""; released: 0 }
        ListElement { gameId: "fake22"; title: "Deep Sky Radio"; source: "battlenet"; sourceName: "BATTLE.NET"; sourceIcon: "applications-games"; code: "DSR"; extId: "dsr"; installed: true; noSlot: false; lastPlayed: 1784764195; added: 1790293795; hidden: false; playtime: 0; developer: ""; publisher: ""; released: 0 }
        ListElement { gameId: "fake23"; title: "Lantern Launcher"; source: "flatpak"; sourceName: "FLATPAK"; sourceIcon: "applications-games"; code: "LALA"; extId: "lala"; installed: true; noSlot: true; lastPlayed: 1784504995; added: 1790380195; hidden: false; playtime: 0; developer: ""; publisher: ""; released: 0 }
    }

    property ListModel sessions: ListModel {
        signal ending(string gameId, string reason)
        signal stateChanged(string gameId, string state)
        function index(r, c) { return r }
        function data(i, role) { return "" }
        function indexOf(id) { return -1 }
        function canSwitch(id) { return false }
        function quit(id) {}
        function forceQuit(id) {}
        function keepWaiting(id) {}
        function eject(id) {}
        function release(id) {}
        function switchTo(id) { return false }
    }

    property QtObject status: QtObject {
        signal changed()
        property bool steamRunning: true
        property int total: 24
        property int installed: 20
    }

    property QtObject installs: QtObject {
        signal changed()
        property var progress: ({})
        function simulate(id, f) {}
    }

    property QtObject keys: QtObject {
        signal changed()
        property var has: ({"steamgrid": true, "steam": true})
        property var status: ({})
        property var message: ({})
        function save(s, k) {}
        function remove(s) {}
    }

    property QtObject updater: QtObject {
        signal changed()
        property string version: "0.2.0"
        property string latest: ""
        property bool available: false
        property bool checking: false
        function check() {}
        function download() {}
    }

    property QtObject store: QtObject {
        signal featuredReady(var list)
        signal spotlightReady(var list)
        signal chartsReady(var list)
        signal categoryReady(int tag, var list)
        signal searchReady(string term, var list)
        signal searchFailed(string term)
        signal categoryFailed(int tag)
        signal detailsReady(int appid, var info)
        signal extrasReady(string key, var data)
        signal failed(string message)
        property var categories: []
        property var categoryArt: ({})
        function loadFeatured() {}
        function loadSpotlight() {}
        function loadCharts() {}
        function loadCategory(t) {}
        function loadAllCategoryArt() {}
        function search(t) {}
        function loadDetails(a) {}
        function loadDetailsQuiet(a) {}
        function loadExtras(k, a, t) {}
    }

    property QtObject artPicker: QtObject {
        signal candidatesReady(string gameId, var list)
        signal searchResults(string term, var list)
        signal choiceFailed(string gameId, string message)
        signal chosen(string gameId)
        property int pending: 0
        function loadCandidates(id, kind) {}
        function searchGames(t) {}
        function useSgdbGame(id, s) {}
        function choose(id, url) {}
        function chooseFile(id, p) {}
        function cropInfo(id) { return ({"cx": 0.5, "cy": 0.5, "zoom": 1}) }
        function setCrop(id, x, y, z) {}
        function reset(id) {}
        function retryMissing() {}
        function fetch_logo_slot(id) {}
    }
}
