#!/usr/bin/env python3
"""Stand-in data so Carthage's screens open in a visual QML editor (Qt Creator's Design
mode / Qt Design Studio) and in the `qml` previewer.

Every screen asks the Python engine (the `Backend` singleton, `import Carthage`) for its
colors, sizes and games; an editor doesn't run Python, so without this the screens come up
blank. qml/carthage.qmlproject adds qml/designer/ to the import path, where a stand-in
`Carthage` module provides a QML `Backend` singleton. This script writes that singleton
from the real theme, settings and demo library, so re-run it after changing theme.py or
settings.py:

    python tools/make_designer_data.py

What still doesn't show in an editor: pictures painted by Python (the plastic shells,
pockets, shadows, icons: image://gc/…) and the 3D card. Layout, text, colors and every
control do.
"""

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from carthage import theme  # noqa: E402
from carthage.library import SOURCES, fake_games  # noqa: E402
from carthage.settings import Settings  # noqa: E402
from carthage.version import VERSION  # noqa: E402

OUT = ROOT / "carthage" / "qml" / "designer" / "Carthage" / "Backend.qml"


def js(value):
    """A value as QML/JavaScript. Objects get parentheses: after a colon, a bare {…} would
    read as a code block."""
    text = json.dumps(value, ensure_ascii=False)
    return f"({text})" if isinstance(value, dict) else text


def main():
    edition = "dark"
    pal = {k: v for k, v in theme.EDITIONS[edition].items()}
    hardware = [{"value": k, "text": n, "color": theme.EDITIONS[e]["shellTop"]} for k, e, n in theme.HARDWARE]
    settings = dict(Settings.DEFAULTS)
    games = []
    for g in fake_games():
        games.append({
            "gameId": g.game_id, "title": g.title, "source": g.source, "sourceName": SOURCES[g.source][0],
            "sourceIcon": SOURCES[g.source][1], "code": g.code, "extId": g.ext_id, "installed": g.installed,
            "noSlot": g.no_slot, "lastPlayed": g.last_played, "added": g.added, "hidden": False,
            "playtime": g.playtime, "developer": g.developer, "publisher": g.publisher, "released": g.released,
        })
    elements = "\n".join(
        "        ListElement { " + "; ".join(f"{k}: {js(v)}" for k, v in g.items()) + " }" for g in games)
    settings_props = "\n".join(
        f"        property {('bool' if isinstance(v, bool) else 'real' if isinstance(v, float) else 'int' if isinstance(v, int) else 'string' if isinstance(v, str) else 'var')} {k}: {js(v)}"
        for k, v in settings.items())

    qml = f"""// GENERATED by tools/make_designer_data.py — don't edit by hand; re-run the script.
// A stand-in `Backend` for visual QML editors and the `qml` previewer: the real theme,
// settings and demo library, with every action doing nothing.
pragma Singleton
import QtQuick

QtObject {{

    property bool fake: true
    property bool firstRun: false
    property real motion: 1
    property int artTick: 0
    property int artGen: 0
    property int headerTick: 0

    signal libraryError(string details)
    signal headerImageFailed(string message)

    function launch(id) {{ return "test" }}
    function gameInfo(id) {{ return ({{}}) }}
    function titleOf(id) {{ return "" }}
    function headerOf(id) {{ return "launcher" }}
    function headerTextOf(id) {{ return "" }}
    function setHeader(id, mode) {{}}
    function setHeaderText(id, t) {{}}
    function setHeaderImage(id, p) {{}}
    function isInstalled(id) {{ return true }}
    function isFavorite(id) {{ return false }}
    function setFavorite(id, on) {{}}
    function playtimeEditable(id) {{ return false }}
    function playtimeHours(id) {{ return "0" }}
    function setPlaytime(id, t) {{ return true }}
    function artRevOf(id) {{ return 0 }}
    function soundUrl(name) {{ return "" }}
    function openUrl(u) {{}}
    function rename(id, t) {{}}
    function setHidden(id, h) {{}}
    function setNoSlot(id, v) {{}}
    function addGame(n, c) {{ return "" }}
    function removeCustomGame(id) {{}}
    function relatedOf(id) {{ return "" }}
    function setRelated(id, n) {{}}
    function processesSince(id) {{ return [] }}
    function libraryIdForApp(a) {{ return "" }}
    function libraryProblems() {{ return "" }}
    function logFile() {{ return "" }}
    function localPath(u) {{ return u }}
    function launcherSummary() {{ return "" }}
    function setupFinished() {{}}
    function rescan() {{}}
    function cacheSize() {{ return "12 MB" }}
    function clearCache() {{ return "12 MB" }}
    function resetSettings() {{}}
    function demoFinishInstall(id) {{}}

    property QtObject theme: QtObject {{
        signal changed()
        property var p: {js(pal)}
        property var cp: p
        property var accent: {js(theme.accent_for(edition))}
        property var led: {js(theme.LED)}
        property var geo: {js(theme.GEOMETRY)}
        property real ratio: {theme.REF_H / theme.REF_W}
        property string edition: "{edition}"
        property string cardEdition: "{edition}"
        property bool dark: true
        property string texQuery: ""
        property string hardware: "black"
        property string cardColor: "same"
        property var hardwareOptions: {js(hardware)}
        function tones(h) {{ return {js(__import__("carthage.colors", fromlist=["x"]).tones(250))} }}
        function harmonies(c) {{ return {js(__import__("carthage.colors", fromlist=["x"]).harmonies("#f7a8c8"))} }}
        function plasticOf(v) {{ return "#3c3c41" }}
        function hueOf(c) {{ return 250 }}
        function customValue(c) {{ return "c_" + c.replace("#", "") }}
    }}

    property QtObject settings: QtObject {{
        signal changed()
{settings_props}
    }}

    property ListModel favorites: ListModel {{
        function rowOf(id) {{ return -1 }}
        function idAt(r) {{ return "" }}
    }}

    property ListModel games: ListModel {{
        property string filterText: ""
        property string filterMode: "all"
        property string sortMode: "recent"
        function rowOf(id) {{ for (let i = 0; i < count; i++) if (get(i).gameId === id) return i; return -1 }}
        function idAt(r) {{ return r >= 0 && r < count ? get(r).gameId : "" }}
{elements}
    }}

    property ListModel sessions: ListModel {{
        signal ending(string gameId, string reason)
        signal stateChanged(string gameId, string state)
        function index(r, c) {{ return r }}
        function data(i, role) {{ return "" }}
        function indexOf(id) {{ return -1 }}
        function canSwitch(id) {{ return false }}
        function quit(id) {{}}
        function forceQuit(id) {{}}
        function keepWaiting(id) {{}}
        function eject(id) {{}}
        function release(id) {{}}
        function switchTo(id) {{ return false }}
    }}

    property QtObject status: QtObject {{
        signal changed()
        property bool steamRunning: true
        property int total: {len(games)}
        property int installed: {sum(1 for g in games if g["installed"])}
    }}

    property QtObject installs: QtObject {{
        signal changed()
        property var progress: ({{}})
        function simulate(id, f) {{}}
    }}

    property QtObject keys: QtObject {{
        signal changed()
        property var has: ({{"steamgrid": true, "steam": true}})
        property var status: ({{}})
        property var message: ({{}})
        function save(s, k) {{}}
        function remove(s) {{}}
    }}

    property QtObject updater: QtObject {{
        signal changed()
        property string version: "{VERSION}"
        property string latest: ""
        property bool available: false
        property bool checking: false
        function check() {{}}
        function download() {{}}
    }}

    property QtObject store: QtObject {{
        signal featuredReady(var list)
        signal spotlightReady(var list)
        signal chartsReady(var list)
        signal categoryReady(int tag, var list)
        signal searchReady(string term, var list)
        signal searchFailed(string term)
        signal categoryFailed(int tag)
        signal detailsReady(int appid, var info)
        signal extrasReady(string key, var data)
        signal failed(string message)
        property var categories: []
        property var categoryArt: ({{}})
        function loadFeatured() {{}}
        function loadSpotlight() {{}}
        function loadCharts() {{}}
        function loadCategory(t) {{}}
        function loadAllCategoryArt() {{}}
        function search(t) {{}}
        function loadDetails(a) {{}}
        function loadDetailsQuiet(a) {{}}
        function loadExtras(k, a, t) {{}}
    }}

    property QtObject artPicker: QtObject {{
        signal candidatesReady(string gameId, var list)
        signal searchResults(string term, var list)
        signal choiceFailed(string gameId, string message)
        signal chosen(string gameId)
        property int pending: 0
        function loadCandidates(id, kind) {{}}
        function searchGames(t) {{}}
        function useSgdbGame(id, s) {{}}
        function choose(id, url) {{}}
        function chooseFile(id, p) {{}}
        function cropInfo(id) {{ return ({{"cx": 0.5, "cy": 0.5, "zoom": 1}}) }}
        function setCrop(id, x, y, z) {{}}
        function reset(id) {{}}
        function retryMissing() {{}}
        function fetch_logo_slot(id) {{}}
    }}
}}
"""
    OUT.parent.mkdir(exist_ok=True)
    OUT.write_text(qml, encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)} ({len(games)} demo games)")


if __name__ == "__main__":
    main()
